### ISSUE TITLE
Automatic dark-mode switching seems to not work on 0.18.1

### ISSUE THREAD

**Issue by poVoq** [hanubeki/hanubeki-lemmy-themes#1]
Hello. Very nice themes! Thanks for making them.

I tried installing the mint theme on my 0.18.1 Lemmy instance and I can manually switch between the `mint-lt` and `mint-dk` themes, but when I select the plain `mint` one it always uses the light mode regardless of my Firefox browser setting.

I am also wondering what the `alt` versions are (I didn't copy those). Are they needed for the switching to work?

**Comment by hanubeki** [comment]
~~Try https://github.com/hanubeki/hanubeki-lemmy-themes/commit/15b1ae09d045814e793af1bd9c07adcdebb59f78~~
Edit: It seems to need modify more styles.
I have modified few things to work auto dark mode in 0.18.1.

If you have problem with it, feel free to comment here.

For `alt` variant: those changed `secondary` color to non-gray one.

**Comment by hanubeki** [comment]
Now you can try https://github.com/hanubeki/hanubeki-lemmy-themes/commit/062b07c0165f80681772e40359060af80f53930e

**Comment by poVoq** [comment]
Seems to work now. Thanks!
