### ISSUE TITLE
PieFedでダークテーマを使用した際の問題

### ISSUE THREAD

**Issue by karasugawasu** [hanubeki/hanubeki-lemmy-themes#13]
最新版は以下状況です

プロフィール設定のExtra fieldsの背景が白い
![image](https://github.com/user-attachments/assets/de649c1c-1cc0-439e-9eb8-d55f842c7c55)

ユーザプロフィールのポップアップの背景が白い
![image](https://github.com/user-attachments/assets/b1df5351-fb57-48f3-8f0c-0cad46aaeed6)

codeブロックの中の色が少し見づらい
![image](https://github.com/user-attachments/assets/d9e51c26-245f-4116-b61d-953a7792cd29)

**Comment by hanubeki** [comment]
ひとまず対応しました。
![image](https://github.com/user-attachments/assets/21569f36-ca34-4b0f-9c5d-bf6de32f8438)
![image](https://github.com/user-attachments/assets/8d9ac20c-3d37-4dea-879a-90fb72aa65c0)
![image](https://github.com/user-attachments/assets/85327c4d-b30c-4599-b071-a3dc30726de3)

**Comment by karasugawasu** [comment]
ありがとうございます、助かります
