### ISSUE TITLE
Temperature ° signs get oddly spaced on Windows

### ISSUE THREAD

**Issue by poVoq** [hanubeki/hanubeki-lemmy-themes#3]
See discussion here: https://slrpnk.net/comment/2465442 (it has some screenshots).

On Windows (only) the ° degree sign has a strange rendering artefact with the Hanubeki themes, that apparently adds a large space after it.

I have no idea what exactly might be causing this and can't replicate it myself as I have no Windows software at all.

Thanks for looking into it if you can.

**Comment by hanubeki** [comment]
This is caused by specifying Japanese fonts and I won't change this.
Feel free to fork and modify the css to specify european fonts.

**Comment by hanubeki** [comment]
For compling modified scss, remove `[data-bs-theme="light"]` from the second line of bootstrap's `_root.scss`.
Otherwise auto light/dark modes will be broken.
