### ISSUE TITLE
Strong yellow color for new posts/comments

### ISSUE THREAD

**Issue by TheAwiteb** [hanubeki/hanubeki-lemmy-themes#6]
As you can see below, the yellow color is very strong, is good with light themes, but with dark ones is actually bad and I think it's can be better.

![image](https://github.com/user-attachments/assets/ed13a1b9-35fa-4a02-8b7f-ea56e9423aee)

**Comment by TheAwiteb** [comment]
Can you assign this to me, I want to work on it

**Comment by hanubeki** [comment]
You can try https://github.com/hanubeki/hanubeki-lemmy-themes/commit/5236a68d06a3854751f3de95cb278c84a7f51b76

**Comment by TheAwiteb** [comment]
Thank you @hanubeki. I've tried the theme on my lemmy instance, and I actually like it
